server.name: kibana
server.host: 0.0.0.0
server.publicBaseUrl: "http://localhost:5601"

elasticsearch.hosts: ["http://elasticsearch:9200"]
# Credentials provided via environment variables in docker-compose
# elasticsearch.username: kibana_system
# elasticsearch.password: ${KIBANA_SYSTEM_PASSWORD}

xpack.security.encryptionKey: "wMzSA6HvPTMknGtLbRyFjhVN7EYOVHywAFv1nJcHgEc46W6H"
xpack.actions.allowedHosts: ['*']